title: Nhi Vo
email: vongocnhi07@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Nhi's Webiste. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nhinvo.github.io" # the base hostname & protocol for site, e.g. http://example.com
github_username:  nhinvo

# Build settings
# theme: minima
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed

just_the_docs:
  custom_css:
    - "assets/css/custom.css"
    
search_enabled: false  # site search
  
heading_anchors: true  # heading anchors

# Aux links for the upper right navigation
aux_links:
  "Github": 
    - "https://github.com/nhinvo"
  "Google Scholar":
    - "https://scholar.google.com/citations?hl=en&user=mG8z-rwAAAAJ"
  "LinkedIn":
    - "https://www.linkedin.com/in/nhinvo/"

# Makes Aux links open in a new tab
aux_links_new_tab: True

# Footer content - appears at the bottom of every page's main content
back_to_top: true  # Back to top link
back_to_top_text: "Back to top"
footer_content: "Contact: nvo[at]mit[dot]edu"

last_edit_timestamp: true
last_edit_time_format: "%Y-%m-%d"

# Google Analytics tracking 
ga_tracking: "G-502Y4YLYN2"
ga_tracking_anonymize_ip: true

# Dark theme
color_scheme: dark